# Generated by Django 3.1.4 on 2020-12-12 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fecha_Creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado'),
        ),
    ]
