# Generated by Django 3.1.3 on 2020-12-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(),
        ),
    ]
